### ISSUE TITLE
Multiplayer MEG 

### ISSUE THREAD

**Issue by SillyScientists** [Adrodoc55/ApertureCraftVanilla#12]
If one player in this case the blue/orange player goes through the MEG the Portals of the Blue/Orange Person closes and the Portals of the Blue/Purple Person as well. May be you do this with teams?
Generally I had to edit the MEG by myself so that they work.

**Comment by Adrodoc** [comment]
@SillyScientists What version of ACV and Minecraft are you using? The MEG is suppposed to close portals depending on what portal guns the player has in his equipement.
If one person only has a blue and an orange portal gun and walks through a MEG any purple and red portals should not be affected.
I found this dynamic way to be better than using teams.

Maybe both players had all of the portal guns somewhere in their equipment, maybe there is a bug in ACV.
Can you please reply if this information solves the problem?

**Comment by SillyScientists** [comment]
So the installed ACV version is 8.1.2 on 1.9.2.
I've tested it with only me on the server shot all portals switched and had only the blue portal gun in my inventory and it still clears all Portals.

**Comment by Adrodoc** [comment]
@SillyScientists I tried it for myself with a fresh copy and it worked exactly as I expected. Are you maybe mixing up inventory and hotbar? Can you please precisely follow these instructions and tell me if it works for you if you do everything exactly as I was doing it.
- Redownloaded v8.1.2 from [here](https://github.com/Adrodoc55/ApertureCraftVanilla/releases/tag/v8.1.2)
- Copy the demo world to your saves folder and open it in Mc 1.9.2.
- Hit the install button
- Turn on the Portalsystem
- Turn on the MEG System
- Click the Equipement button
- Shoot the four different portals against the wall
- Press Q to drop the purple and red portal gun on the ground (don't pick them up again)
- Walk through the existing MEG

After following these steps only the blue and orange portals disappeared.

If following these steps also works for you, you might have a problem in your target world. Maybe you also have an older version of ACV running in the background and deleting all portals.

**Comment by SillyScientists** [comment]
So I found the Problem ^^
I'eited the MEG so theres a little Problem which we want to solve we added that if you drop the Item that you change the Portal Colour so we add then another tag that it then works with only one Portal Gun in the Inventorry bu thanks :)

**Comment by Adrodoc** [comment]
@SillyScientists Good that it works now :D
If you release any maps or videos about your work please let me know!
