### ISSUE TITLE
How do i use the laser to activate redstone?

### ISSUE THREAD

**Issue by FireFlix-Games** [Adrodoc55/ApertureCraftVanilla#21]
How do i use the laser to activate redstone?

**Comment by Adrodoc** [comment]
@FireFlix-Games You can create a clock to run a command that tests for an entity named "ACV_Laser" in a certain block. There are examples in the corresponding adventure map. Do you need a link to that?

**Comment by FireFlix-Games** [comment]
@Adrodoc Yes, I do need a link to that. thanks.

**Comment by Adrodoc** [comment]
@FireFlix-Games Here is the direkt download Link: http://www.mediafire.com/download/66fl8uooxu9bb9k/ApertureCraft+Vanilla+Map+v.latest.zip
There is also a Minecraft Forum Thread with more information: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/maps/2404875-portal-aperturecraft-vanilla-an-unbeliveable

**Comment by Adrodoc** [comment]
@FireFlix-Games can I close this issue or do you still need help?

**Comment by FireFlix-Games** [comment]
No I don't need help anymore. At least regarding this
