### ISSUE TITLE
Portals Should have a glowing outline

### ISSUE THREAD

**Issue by Ersatz77** [Adrodoc55/ApertureCraftVanilla#8]
![2016-02-15_10 18 04](https://cloud.githubusercontent.com/assets/13609369/13058870/f734f21e-d3da-11e5-8a02-5bd7e184d74d.png)

Create a team for each portal color and set their color to their corresponding portal color.

Use the commands: 
`/entitydata @e[name=ACV_PortalDisplay,score_ACV_COLOR_min=0,score_ACV_COLOR=0]{Glowing:1b}`

`/scoreboard teams join BluePortal @e[name=ACV_PortalDisplay,score_ACV_COLOR_min=0,score_ACV_COLOR=0]`
[make sure to swap out the teams and color scores for each portal]

All commands should be in a repeating command block chain and are not conditional

**Comment by Adrodoc** [comment]
Is there a reason why you wanted the team stuff? In the real portal game any player can see the portals, even through walls.

**Comment by Adrodoc** [comment]
Every wall portal is now glowing, there are no teams.
Floor and ceiling portals are not glowing, because the glowing effect does not work well with the ArmorStands used for the portal display.

**Comment by Ersatz77** [comment]
You need a team in order to change the glowing color, and also my screenshot was taken without the player on any team. I'll try to create a schematic of my commands for you.

**Comment by Adrodoc** [comment]
Ah I see, I was missing `/scoreboard teams option ACV_Blue color blue`

**Comment by Ersatz77** [comment]
Btw there is a team NBT tag that could save you 4 commands if you also add it to the portal display  `{Team:"TEAMNAME"}`

**Comment by Adrodoc** [comment]
@Ersatz77 Thanks for that hint, I didn't know that, I have never actually done anything with teams.
Unfortunately I think I will still need to have four repeating commands like this: `/scoreboard teams join ACV_Blue @a` or do you know of a way to automatically do that?
I wonder, if it is sufficient to only run these commands when the system is started, to get rid of one clock, but I guess that might cause problems in multiplayer when new people enter. The cleanest way is most likely going to be an extra clock for these 4 commands after all. Oh well, should be easy enough to do :D

**Comment by Ersatz77** [comment]
I have all of the scoreboard joining and entitydata changes on it's own clock because mabey I want to disable it for some reason. You also can't run that command when you first run the system because teams need the entity in the world in order to add them to a team.

Also for the vertical portals, In order for the glow to be applied only to the item in the head slot, the armorstand must be a marker, but I think that might cause some issues.

Here are the commands that I use for the whole glowing system: http://www.mediafire.com/download/sc6rwm4k7uzp3r1/Portal+Glow.schematic

**Comment by Adrodoc** [comment]
Thanks for the schematik, it did help me.
I didn't add an extra clock like you did so the glowing effect can't be turned off in ACV.

The nbt tag `{Team:"TEAMNAME"}` didn't work for me, are you sure about it?

**Comment by Ersatz77** [comment]
It seems like that tag is only added with the scoreboard and can't be added in /summon. Or at least that was the case I tested. I checked the wiki and it was added in as a new tag.
